name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * 0'   # Ogni domenica a mezzanotte (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: make docker-build DOCKER_IMAGE=ghcr.io/${{ github.repository_owner }}/umserver

      - name: Push Docker Image (latest tag)
        run: docker push ghcr.io/${{ github.repository_owner }}/umserver:latest